openapi: 3.0.0
info:
  title: wikit OpenApi
  description: wikit Swagger OpenApi description
  contact:
    email: me@developit.ir
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api'
paths:
  '/v1/user/login':
    post:
      summary: user login
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'http://localhost:8080/api/swagger/schemas/user-login'
          application/xml:
            schema:
              $ref: 'http://localhost:8080/api/swagger/schemas/user-login'
        required: true
      responses:
        '200':
          description: Successful created
        '400':
          description: Bad request
        '404':
          description: Resource Not Found
      tags:
        - user
